language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
before_script:

  - wget https://github.com/samtools/htslib/releases/download/1.10/htslib-1.10.tar.bz2
  - tar jxvf htslib-1.10.tar.bz2
  - cd htslib-1.10 && ./configure && make && sudo make install && cd ../

  - wget http://ftp.debian.org/debian/pool/main/m/mafft/mafft_7.407-2_amd64.deb
  - sudo dpkg -i mafft_7.407-2_amd64.deb

  - wget https://github.com/mengyao/Complete-Striped-Smith-Waterman-Library/archive/v1.1.tar.gz
  - tar zxvf v1.1.tar.gz 
  - cd Complete-Striped-Smith-Waterman-Library-1.1/src
  - gcc -Wall -O3 -pipe -fPIC -shared -rdynamic -o libssw.so ssw.c ssw.h
  - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$PWD
  - cd ../..

  - python -m pip install -U setuptools 
  - python -m pip install -U importlib-metadata
  - python -m pip install requests
  - python -m pip install numpy==1.16.6
  - python -m pip install pysam==0.16.0.1
  - python -m pip install parasail==1.2

script:
  - python -m pip install .
  - python setup.py test
